### ISSUE TITLE
为什么状态码不统一？

### ISSUE THREAD

**Issue by Aurorxa** [qingstor/qingstor-sdk-java#208]
创建 bucket ，成功 201

![image](https://user-images.githubusercontent.com/25677587/190557090-2e4d97f0-0603-4608-b93d-4f4db5e55d4a.png)

删除 bucket ，成功 204

![image](https://user-images.githubusercontent.com/25677587/190557172-8efea4a7-dd4a-4a96-bf5e-b45d12c9ba7c.png)

**Comment by owarai** [comment]
主要是 2 点:

1. 这是参考 HTTP method 语义的决定, 可参考 https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE
2. 业界统一做法, 比如 [s3](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html#API_DeleteObject_RequestBody), [阿里云](https://help.aliyun.com/document_detail/31982.html)
