### ISSUE TITLE
页面404

### ISSUE THREAD

**Issue by abc45628** [qingstor/qingstor-sdk-java#98]
https://github.com/qingstor/qingstor-sdk-java/blob/master/docs/guide_zh.md

您可以在这里看到包含完整包结构的SDK文档：github pages。

github pages。指向的连接失效了

**Comment by owarai** [comment]
目前我们觉得在 javadoc.io 没有必要再在仓库内维护 docs, 可以使用 https://javadoc.io/doc/com.yunify/qingstor.sdk.java 来阅读.

我们会更新一下连接.
